Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
ты на главной странице! 
"GET / HTTP/1.1" 200 553
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2953
ты читаешь текст про меня
"GET /about_me/ HTTP/1.1" 200 1000
ты на главной странице! 
"GET / HTTP/1.1" 200 553
Ответ game_1   равен : Орёл
"GET /game_1/ HTTP/1.1" 200 8
Ответ game_1   равен : Решка
"GET /game_1/ HTTP/1.1" 200 10
Ответ game_1   равен : Орёл
"GET /game_1/ HTTP/1.1" 200 8
Ответ game_1   равен : Орёл
"GET /game_1/ HTTP/1.1" 200 8
Ответ game_1   равен : Орёл
"GET /game_1/ HTTP/1.1" 200 8
Ответ game_1   равен : Орёл
"GET /game_1/ HTTP/1.1" 200 8
Ответ game_1   равен : Орёл
"GET /game_1/ HTTP/1.1" 200 8
Ответ game_1   равен : Решка
"GET /game_1/ HTTP/1.1" 200 10
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
Ответ game_1   равен : Решка
"GET /game_1/ HTTP/1.1" 200 10
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
Ответ game_1   равен : Решка
"GET /game_1/ HTTP/1.1" 200 10
Ответ game_1   равен : Орёл
"GET /game_1/ HTTP/1.1" 200 8
Ответ game_1   равен : Орёл
"GET /game_1/ HTTP/1.1" 200 8
Ответ game_1   равен : Орёл
"GET /game_1/ HTTP/1.1" 200 8
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
Ответ game_1   равен : Решка
"GET /game_1/ HTTP/1.1" 200 10
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /static_game/ HTTP/1.1" 200 4
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /static_game/ HTTP/1.1" 200 4
"GET /static_game/ HTTP/1.1" 200 4
"GET /static_game/ HTTP/1.1" 200 4
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /static_game/ HTTP/1.1" 200 4
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /static_game/ HTTP/1.1" 200 4
"GET /static_game/ HTTP/1.1" 200 4
"GET /static_game/ HTTP/1.1" 200 4
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /static_game/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 23, in static_game
    count = Coin.count_trow()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py", line 20, in count_trow
    if item.site == 'орел':
       ^^^^^^^^^
AttributeError: 'Coin' object has no attribute 'site'
"GET /static_game/ HTTP/1.1" 500 68795
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /static_game/ HTTP/1.1" 200 18
"GET /static_game/ HTTP/1.1" 200 18
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /static_game/ HTTP/1.1" 200 18
"GET /static_game/ HTTP/1.1" 200 18
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /static_game/ HTTP/1.1" 200 18
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /static_game/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 23, in static_game
    count = Coin.count_trow()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py", line 23, in count_trow
    dict_coin['решка'] +=1
    ~~~~~~~~~^^^^^^^^^
KeyError: 'решка'
"GET /static_game/ HTTP/1.1" 500 68634
Internal Server Error: /static_game/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 23, in static_game
    count = Coin.count_trow()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py", line 23, in count_trow
    dict_coin['Решка'] +=1
    ~~~~~~~~~^^^^^^^^^
KeyError: 'решка'
"GET /static_game/ HTTP/1.1" 500 68634
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /static_game/ HTTP/1.1" 200 18
"GET /static_game/ HTTP/1.1" 200 18
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /static_game/ HTTP/1.1" 200 18
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /static_game/ HTTP/1.1" 200 28
"GET /static_game/ HTTP/1.1" 200 28
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /full_name/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 42, in full_name
    full_name = Autor.full_name()
                ^^^^^^^^^^^^^^^^^
TypeError: Autor.full_name() missing 3 required positional arguments: 'self', 'name', and 'surname'
"GET /full_name/ HTTP/1.1" 500 64186
Watching for file changes with StatReloader
Internal Server Error: /full_name/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 45, in full_name
    result += f'{item.full_name()}\n'
                 ^^^^^^^^^^^^^^^^
TypeError: Autor.full_name() missing 2 required positional arguments: 'name' and 'surname'
"GET /full_name/ HTTP/1.1" 500 65167
Internal Server Error: /full_name/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 45, in full_name
    result += f'{item.full_name()}\n'
                 ^^^^^^^^^^^^^^^^
TypeError: Autor.full_name() missing 2 required positional arguments: 'name' and 'surname'
"GET /full_name/ HTTP/1.1" 500 65167
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
ты на главной странице! 
"GET / HTTP/1.1" 200 553
Internal Server Error: /full_name/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 45, in full_name
    result += f'{item.full_name()}\n'
                 ^^^^^^^^^^^^^^^^
TypeError: Autor.full_name() missing 2 required positional arguments: 'name' and 'surname'
"GET /full_name/ HTTP/1.1" 500 65146
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /full_name/ HTTP/1.1" 200 172
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /full_name/ HTTP/1.1" 200 182
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /full_name/ HTTP/1.1" 200 202
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
ты на главной странице! 
"GET / HTTP/1.1" 200 553
ты читаешь текст про меня
Internal Server Error: /about_me/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 40, in about_me
    return render(request, 'firstapp/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'endblock'. Did you forget to register or load this tag?
"GET /about_me/ HTTP/1.1" 500 151733
ты читаешь текст про меня
Internal Server Error: /about_me/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 40, in about_me
    return render(request, 'firstapp/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'endblock'. Did you forget to register or load this tag?
"GET /about_me/ HTTP/1.1" 500 151870
ты на главной странице! 
"GET / HTTP/1.1" 200 553
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\urls.py changed, reloading.
Watching for file changes with StatReloader
ты на главной странице! 
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 12, in index
    return render(request, 'firstapp/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    raise TemplateSyntaxError(error_msg)
django.template.exceptions.TemplateSyntaxError: Invalid template name in 'extends' tag: ''. Got this from the 'base.html' variable.
"GET / HTTP/1.1" 500 108574
ты на главной странице! 
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 12, in index
    return render(request, 'firstapp/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET / HTTP/1.1" 500 128545
ты на главной странице! 
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 12, in index
    return render(request, 'firstapp/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET / HTTP/1.1" 500 128545
ты на главной странице! 
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 12, in index
    return render(request, 'firstapp/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET / HTTP/1.1" 500 128545
C:\Users\Petr\PycharmProjects\django\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
ты на главной странице! 
"GET / HTTP/1.1" 200 176
ты на главной странице! 
"GET / HTTP/1.1" 200 176
ты на главной странице! 
"GET /about/ HTTP/1.1" 200 180
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
ты на главной странице! 
"GET /about/ HTTP/1.1" 200 180
 game_2   равен : 1
"GET /game_2/ HTTP/1.1" 200 137
 game_2   равен : 2
"GET /game_2/ HTTP/1.1" 200 137
 game_2   равен : 2
"GET /game_2/ HTTP/1.1" 200 137
 game_2   равен : 4
"GET /game_2/ HTTP/1.1" 200 137
 game_2   равен : 4
"GET /game_2/ HTTP/1.1" 200 137
 game_2   равен : 6
"GET /game_2/ HTTP/1.1" 200 137
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
Ответ game_1   равен : Орёл
"GET /game_1/ HTTP/1.1" 200 144
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
Ответ game_3   равен : 0
"GET /game_3/ HTTP/1.1" 200 137
Ответ game_3   равен : 85
"GET /game_3/ HTTP/1.1" 200 138
Ответ game_3   равен : 66
"GET /game_3/ HTTP/1.1" 200 138
Ответ game_3   равен : 67
"GET /game_3/ HTTP/1.1" 200 138
Ответ game_3   равен : 70
"GET /game_3/ HTTP/1.1" 200 138
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /author/1 HTTP/1.1" 200 144
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /author/1 HTTP/1.1" 200 144
"GET /author/1 HTTP/1.1" 200 144
"GET /author/1 HTTP/1.1" 200 144
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /author/1 HTTP/1.1" 200 144
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /author/1 HTTP/1.1" 200 144
Internal Server Error: /author/1
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'ifpost.is_published'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 66, in show_posts
    return render(request, 'firstapp/posts.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\defaulttags.py", line 860, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'ifpost.is_published', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
"GET /author/1 HTTP/1.1" 500 184531
"GET /author/1 HTTP/1.1" 200 303
"GET /author/1 HTTP/1.1" 200 303
"GET /author/1 HTTP/1.1" 200 303
"GET /author/1 HTTP/1.1" 200 303
"GET /author/1 HTTP/1.1" 200 303
"GET /author/1 HTTP/1.1" 200 303
"GET /author/1 HTTP/1.1" 200 303
Watching for file changes with StatReloader
"GET /author/1 HTTP/1.1" 200 303
"GET /author/1 HTTP/1.1" 200 303
"GET /author/1 HTTP/1.1" 200 301
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /author/1 HTTP/1.1" 200 301
"GET /author/1 HTTP/1.1" 200 301
"GET /author/1 HTTP/1.1" 200 301
"GET /author/1 HTTP/1.1" 200 301
"GET /author/1 HTTP/1.1" 200 301
"GET /author/1 HTTP/1.1" 200 301
ты на главной странице! 
"GET / HTTP/1.1" 200 176
"GET /author/1 HTTP/1.1" 200 301
"GET /author/2 HTTP/1.1" 200 301
"GET /author/2 HTTP/1.1" 200 308
"GET /author/2 HTTP/1.1" 200 308
"GET /author/1 HTTP/1.1" 200 308
"GET /author/1 HTTP/1.1" 200 308
"GET /author/1 HTTP/1.1" 200 308
"GET /author/1 HTTP/1.1" 200 308
"GET /author/1 HTTP/1.1" 200 308
"GET /author/1 HTTP/1.1" 200 308
"GET /author/1 HTTP/1.1" 200 1058
"GET /author/5 HTTP/1.1" 200 1058
"GET /author/6 HTTP/1.1" 200 1307
"GET /author/1 HTTP/1.1" 200 1058
"GET /author/2 HTTP/1.1" 200 1058
"GET /author/2 HTTP/1.1" 200 1322
"GET /author/1 HTTP/1.1" 200 1256
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /author/1 HTTP/1.1" 200 1286
Not Found: /author/{% url 'show_post_id' post.id %
"GET /author/%7B%%20url%20'show_post_id'%20post.id%20% HTTP/1.1" 404 3985
Watching for file changes with StatReloader
Not Found: /author/{% url 'show_post_id' post.id %
"GET /author/%7B%%20url%20'show_post_id'%20post.id%20% HTTP/1.1" 404 3985
Not Found: /author/{% url 'show_post_id' post.id %
"GET /author/%7B%%20url%20'show_post_id'%20post.id%20% HTTP/1.1" 404 3985
Watching for file changes with StatReloader
"GET /author/1 HTTP/1.1" 200 1142
"GET /post/8 HTTP/1.1" 200 168
"GET /post/1 HTTP/1.1" 200 168
"GET /post/4 HTTP/1.1" 200 168
"GET /post/3 HTTP/1.1" 200 168
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clients/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: shop/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 77, in client_list
    return render(request, 'firstapp/client_list.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: shop/base.html
"GET /clients/ HTTP/1.1" 500 147316
Internal Server Error: /clients/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: firstapp/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 77, in client_list
    return render(request, 'firstapp/client_list.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: firstapp/base.html
"GET /clients/ HTTP/1.1" 500 147609
Internal Server Error: /clients/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: firstapp/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 77, in client_list
    return render(request, 'firstapp/client_list.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: firstapp/base.html
"GET /clients/ HTTP/1.1" 500 147609
Internal Server Error: /clients/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 77, in client_list
    return render(request, 'firstapp/client_list.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\urls\resolvers.py", line 848, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'client_detail' not found. 'client_detail' is not a valid view function or pattern name.
"GET /clients/ HTTP/1.1" 500 195109
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Petr\PycharmProjects\django\myproject\firstapp\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
ты на главной странице! 
"GET / HTTP/1.1" 200 208
"GET /order/1 HTTP/1.1" 301 0
Internal Server Error: /order/1/
Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: firstapp_orders

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\myproject\firstapp\views.py", line 81, in order_full
    order = get_object_or_404(Orders, pk=order_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Petr\PycharmProjects\django\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: firstapp_orders
"GET /order/1/ HTTP/1.1" 500 134963
